version: "2"

plugins:
  duplication:
    enabled: true
    config:
      languages:
        - php

  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR2"

exclude_patterns:
  - "tests/"
  - "**.md"
  - "**.json"
  - "**.xml"
